### ISSUE TITLE
log warnings after update js-Controller to 3.3.x

### ISSUE THREAD

**Issue by ausbremen** [iobroker-community-adapters/ioBroker.fhem#108]
Nach Update des js-Controllers auf Version 3.3x wird nachfolgendes im Log angezeigt.

fhem.0 | 2021-05-01 14:33:41.846 | warn | (1048) State value to set for "fhem.0.ValloxSE.FireplaceSwitchActivation" has wrong type "string" but has to be "number"
-- | -- | -- | --
fhem.0 | 2021-05-01 14:33:41.807 | warn | (1048) State value to set for "fhem.0.ValloxSE.ServiceReminderIndicator" has wrong type "string" but has to be "number"
fhem.0 | 2021-05-01 14:33:41.807 | warn | (1048) State value to set for "fhem.0.ValloxSE.HeatingState" has wrong type "string" but has to be "number"
fhem.0 | 2021-05-01 14:33:41.807 | warn | (1048) State value to set for "fhem.0.ValloxSE.RHAdjustState" has wrong type "string" but has to be "number"
fhem.0 | 2021-05-01 14:33:41.806 | warn | (1048) State value to set for "fhem.0.ValloxSE.CO2AdjustState" has wrong type "string" but has to be "number"
fhem.0 | 2021-05-01 14:33:41.803 | warn | (1048) State value to set for "fhem.0.ValloxSE.PowerState" has wrong type "string" but has to be "number"
fhem.0 | 2021-05-01 14:33:41.791 | warn | (1048) State value to set for "fhem.0.ValloxSE.FanSpeedPct" has wrong type "string" but has to be "number"
fhem.0 | 2021-05-01 14:33:41.765 | warn | (1048) State value to set for "fhem.0.ValloxSE.FanSpeed" has wrong type "string" but has to be "number"
fhem.0 | 2021-05-01 14:33:41.748 | warn | (1048) State value to set for "fhem.0.ValloxSE.ServiceReminderIndicator" has wrong type "string" but has to be "number"
fhem.0 | 2021-05-01 14:33:41.747 | warn | (1048) State value to set for "fhem.0.ValloxSE.HeatingState" has wrong type "string" but has to be "number"
fhem.0 | 2021-05-01 14:33:41.747 | warn | (1048) State value to set for "fhem.0.ValloxSE.RHAdjustState" has wrong type "string" but has to be "number"
fhem.0 | 2021-05-01 14:33:41.747 | warn | (1048) State value to set for "fhem.0.ValloxSE.CO2AdjustState" has wrong type "string" but has to be "number"
fhem.0 | 2021-05-01 14:33:41.746 | warn | (1048) State value to set for "fhem.0.ValloxSE.PowerState" has wrong type "string" but has to be "number"
info.0 | 2021-05-01 14:33:41.293 | warn | (567) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-05-01 14:33:41.052 | warn | (567) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
info.0 | 2021-05-01 14:33:38.315 | warn | (567) State value to set for "info.0.sysinfo.cpu.temperature.cores" has wrong type "object" but has to be "string"
info.0 | 2021-05-01 14:33:38.054 | warn | (567) State value to set for "info.0.sysinfo.cpu.currentspeed.coresSpeed" has wrong type "object" but has to be "string"
fhem.0 | 2021-05-01 14:33:36.684 | warn | (1048) State value to set for "fhem.0.ValloxSE.FireplaceSwitchActivation" has wrong type "string" but has to be "num

I read, that this is a new check in js-Controller and the developer of the adapter has to change something...

Best regards
Holger

**Comment by Apollon77** [comment]
Plese try GitHub version - or next release tomorrow 1.6.1
