### ISSUE TITLE
v. 0.5.0 trying to reconnect and stops with failure frequently.

### ISSUE THREAD

**Issue by RalfM04** [iobroker-community-adapters/ioBroker.fhem#11]
The fhem adapter is trying to connect to fhem Server and stops with error,  
[IO_Broker_LOG.txt](https://github.com/ioBroker/ioBroker.fhem/files/2306704/IO_Broker_LOG.txt)

The Jsonlist2 result can be found in this file
[JSONLIST2.txt](https://github.com/ioBroker/ioBroker.fhem/files/2306731/JSONLIST2.txt)

Version 0.4.2 works without this problem.

**Comment by GermanBluefox** [comment]
Thank you. Will check it.

**Comment by LausiD** [comment]
edit like this to catch the error ?

for (var i = 0; i < objs.length; i++) {
            try {
                if (objs[i].Attributes.room) suche = objs[i].Attributes.room;
                if (suche.indexOf('ioBroker') !== -1) {
                    iobroker = true;
                    continue;
                }
            } catch (err) {
                     adapter.log.error('[parseObjects] Cannot check room of object: ' + JSON.stringify(objs[i]));
                     adapter.log.error('[parseObjects] Cannot check room of object: ' + err);
            }
        }

**Comment by Apollon77** [comment]
Send pr ;-)

**Comment by RalfM04** [comment]
Hello, I tried to replace your Code with the actual on efrom v.0.5.0.
I found this under function parse objects.

I replaced like this:

   if (firstRun == true) {
        adapter.log.info('last update: 29.04.18 LausiD ');
        adapter.log.info('Settings: ignored PossibleSets: ' + ignorePossibleSets);
        adapter.log.info('Settings: role button PossibleSets: noArg');
        adapter.log.info('Settings: role level.xxx PossibleSets: slider');
        adapter.log.info('Settings: role level.temperature PossibleSets: desired-temp');
        adapter.log.info('Settings: role level.volume PossibleSets: ' + volumePossibleSets);
        adapter.log.info('Settings: role level.dimmer PossibleSets: ' + dimPossibleSets);
        adapter.log.info('Settings: ignored Readings: ' + ignoreReadings);
        adapter.log.info('Settings: allowed Internals: ' + allowedInternals);
        adapter.log.info('Settings: allowed attributes: ' + allowedAttributes);
        for (var i = 0; i < objs.length; i++) {
            if (objs[i].Attributes.room) suche = objs[i].Attributes.room;
            if (suche.indexOf('ioBroker') != -1) iobroker = true;
        }
        adapter.log.info('Settings: room ioBroker = ' + iobroker);
        adapter.log.info('Settings: channels found = ' + objs.length);
    }

    for (var i = 0; i < objs.length; i++) {
        try {
            name = objs[i].Name.replace(/\./g, '_');
            var searchRoom = 'no';
            if (objs[i].Attributes.room) suche = objs[i].Attributes.room;
            if (suche.indexOf('ioBroker') !== -1) {
                iobroker = true;
                continue;
            }
            } catch (err) {
            adapter.log.error('[parseObjects] Cannot check room of object: ' + JSON.stringify(objs[i]));
            adapter.log.error('[parseObjects] Cannot check room of object: ' + err);
            }
            }
            if (firstRun == true) adapter.log.info('Check channel ' + adapter.namespace + '.' + name + ' | room: ' + objs[i].Attributes.room + ' [' + (i + 1) + '/' + objs.length + ']');
            id = adapter.namespace + '.' + name;

It doesn’t work.
Here are the LOG results.

host.ioBroker-RasPi
2018-08-21 21:00:50.522
error
instance system.adapter.fhem.0 terminated with code 1 ()
host.ioBroker-RasPi
2018-08-21 21:00:50.522
error
Caught by controller[0]: at bootstrap_node.js:609:3
host.ioBroker-RasPi
2018-08-21 21:00:50.522
error
Caught by controller[0]: at startup (bootstrap_node.js:188:16)
host.ioBroker-RasPi
2018-08-21 21:00:50.522
error
Caught by controller[0]: at Function.Module.runMain (module.js:693:10)
host.ioBroker-RasPi
2018-08-21 21:00:50.522
error
Caught by controller[0]: at Function.Module._load (module.js:497:3)
host.ioBroker-RasPi
2018-08-21 21:00:50.522
error
Caught by controller[0]: at tryModuleLoad (module.js:505:12)
host.ioBroker-RasPi
2018-08-21 21:00:50.521
error
Caught by controller[0]: at Module.load (module.js:565:32)
host.ioBroker-RasPi
2018-08-21 21:00:50.521
error
Caught by controller[0]: at Object.Module._extensions..js (module.js:663:10)
host.ioBroker-RasPi
2018-08-21 21:00:50.521
error
Caught by controller[0]: at Module._compile (module.js:616:28)
host.ioBroker-RasPi
2018-08-21 21:00:50.521
error
Caught by controller[0]: at Object.runInThisContext (vm.js:139:10)
host.ioBroker-RasPi
2018-08-21 21:00:50.521
error
Caught by controller[0]: at createScript (vm.js:80:10)
host.ioBroker-RasPi
2018-08-21 21:00:50.521
error
Caught by controller[0]: SyntaxError: Unexpected token catch
host.ioBroker-RasPi
2018-08-21 21:00:50.521
error
Caught by controller[0]: ^^^^^
host.ioBroker-RasPi
2018-08-21 21:00:50.520
error
Caught by controller[0]: } catch (err) {
host.ioBroker-RasPi
2018-08-21 21:00:50.520
error
Caught by controller[0]: /opt/iobroker/node_modules/iobroker.fhem/main.js:665
host.ioBroker-RasPi
2018-08-21 21:00:50.166
info
instance system.adapter.fhem.0 started with pid 12347
host.ioBroker-RasPi
2018-08-21 21:00:20.141
info
Restart adapter system.adapter.fhem.0 because enabled
Please be aware that I’m not the Scripting expert.

Regards
Ralf


Von: LausiD
Gesendet: Dienstag, 21. August 2018 19:30
An: ioBroker/ioBroker.fhem
Cc: RalfM04; Author
Betreff: Re: [ioBroker/ioBroker.fhem] v. 0.5.0 trying to reconnect and stopswith failure frequently. (#11)

edit like this to catch the error ?
for (var i = 0; i < objs.length; i++) {
try {
for (var i = 0; i < objs.length; i++) {
continue;
}
} catch (err) {
adapter.log.error('[parseObjects] Cannot check room of object: ' + JSON.stringify(objs[i]));
adapter.log.error('[parseObjects] Cannot check room of object: ' + err);
}
}

**Comment by LausiD** [comment]
Just a moment RalfM04.....please wait for the new version 0.5.3 :-)

**Comment by LausiD** [comment]
@RalfM04 Now update from github

**Comment by RalfM04** [comment]
Thx a lot, 
it seems to work.

I received one object which is stored in the ioBroker room.
Tomorrow I’ll try to test if i delete this room if I will receive all objects.



Gesendet von Mail für Windows 10

Von: LausiD
Gesendet: Dienstag, 21. August 2018 21:36
An: ioBroker/ioBroker.fhem
Cc: RalfM04; Mention
Betreff: Re: [ioBroker/ioBroker.fhem] v. 0.5.0 trying to reconnect and stopswith failure frequently. (#11)

@RalfM04 Now update from github
