### ISSUE TITLE
TypeError: Cannot read property 'startsWith' of undefined [main] [eventFHEM] [processEvent] [parseEvent]

### ISSUE THREAD

**Issue by aski71** [iobroker-community-adapters/ioBroker.fhem#116]
I keep getting this error in my log:

TypeError: Cannot read property 'startsWith' of undefined [main] [eventFHEM] [processEvent] [parseEvent]

**Comment by Apollon77** [comment]
Can you please show more log? Just one line is mostly not that helpful. Best also set debug loglevel

**Comment by Apollon77** [comment]
I found a place that could it be ... please try GitHub version or next version officially availabketomorrow

**Comment by aski71** [comment]
Ok, I'll wait for the next official version. If the problem persist, I'll increase the log level.

**Comment by aski71** [comment]
The issue is revolved. Thanks.
