### ISSUE TITLE
allowedIOBin issues to create devices on fhem

### ISSUE THREAD

**Issue by ohobby** [iobroker-community-adapters/ioBroker.fhem#126]
Kann es sein, dass der Adapter ein Problem mit dem @ hat?
Bis jetzt wurde alles was in allowedIOBin eingetragen wurde auch auf dem FHEM angelegt.
Wenn ich jetzt mqtt.7.v3.mini-lora-wetter@ttn.devices.cube-cell-ost eintrage oder nur einen Teil davon, wird das nicht auf dem FHEM abgebildet.
Auf dem iobroker ist im Log zu sehen, das es eigentlich gemacht sein sollte. Aber auf dem fhem ist nichts angelegt worden.

fhem.0 | 2021-08-14 22:37:32.442 | info | STEP 13 ==== processed saved stateChange(s) of ioBroker
-- | -- | -- | --
fhem.0 | 2021-08-14 22:37:32.442 | info | > save FHEM: Wrote configuration to fhem.cfg
fhem.0 | 2021-08-14 22:37:32.442 | info | > activate fhem.0.alive room ioB_System every 5 minutes
fhem.0 | 2021-08-14 22:37:32.441 | info | STEP 12 ==== activate alive and save FHEM
-- | -- | -- | --
fhem.0 | 2021-08-14 22:37:32.441 | info | > dummy fhem.0.alive - use to check alive FHEM Adapter in FHEM
fhem.0 | 2021-08-14 22:37:32.441 | info | > dummy fhem.0.send2ioB - use to set objects/states of ioBroker from FHEM
fhem.0 | 2021-08-14 22:37:32.383 | info | > create dummy mqtt.7.v3.mini_lora_wetter@ttn.devices.cube_cell_ost.Data.Temperature / Temperature
fhem.0 | 2021-08-14 22:37:32.383 | info | > create dummy mqtt.7.v3.mini_lora_wetter@ttn.devices.cube_cell_ost.Data.Pressure / Pressure
fhem.0 | 2021-08-14 22:37:32.383 | info | > create dummy mqtt.7.v3.mini_lora_wetter@ttn.devices.cube_cell_ost.Data.LastChange / LastChange
fhem.0 | 2021-08-14 22:37:32.383 | info | > create dummy mqtt.7.v3.mini_lora_wetter@ttn.devices.cube_cell_ost.Data.Humidity / Humidity
fhem.0 | 2021-08-14 22:37:32.383 | info | > create dummy mqtt.7.v3.mini_lora_wetter@ttn.devices.cube_cell_ost.Data.Battery / Battery
fhem.0 | 2021-08-14 22:37:32.383 | info | > create dummy mqtt.7.v3.mini_lora_wetter@ttn.devices.cube_cell_ost.up / v3/mini-lora-wetter@ttn/devices/cube-cell-ost/up
fhem.0 | 2021-08-14 22:37:32.372 | info | STEP 11 ==== check/create FHEM dummy Devices in room ioB_IN/ioB_System

**Comment by ohobby** [comment]
Ich glaube es funktioniert nicht, weil das @ Zeichen in FHEM Namen nicht erlaubt ist.
Evtl. sollte man da dann eine Fehlermeldung einbauen und evtl. eine Funktion einbauen, die mit sowas dann umgeht (das Zeichen weg lässt oder ein Ersatzzeichen einsetzt).

**Comment by LausiD** [comment]
Korrekt......@ ist in FHEM nicht erlaubt.
Bitte Update von github und testen. 
Danke :-)
