### ISSUE TITLE
Cannot read property 'split' of null

### ISSUE THREAD

**Issue by Cupra-Bo** [iobroker-community-adapters/ioBroker.fhem#138]
Please help
Fhem as Docker telenet port is set
ioBroker as Docker 

![fhem](https://user-images.githubusercontent.com/65092666/139560673-be6801bb-bbf9-453a-95cd-8df539d0a0f9.png)

**Comment by LausiD** [comment]
Versuche mal bitte unter fhem.0.info.Debug.activate etwas einzutragen zB "Test" und danach Adapter starten

**Comment by Cupra-Bo** [comment]
Jetzt ist alles im Grünen bereich ;)
