### ISSUE TITLE
different (not) allowed characters for object names

### ISSUE THREAD

**Issue by RVE1** [iobroker-community-adapters/ioBroker.fhem#152]
Iobroker and Fhem are using different characters for objects. With Fhem only the following characters can be used A-Za-z0-9._ .  I have an ioBroker module in use which has a / in its object name. So it is not possible to provide this object via the entry in fhem.x.info.Configurations.allowedIOBin.

1. Fhem:
define name/name1.name dummy
2. See error:
Invalid characters in name (not A-Za-z0-9._): name/name1.name

It would make sense to translate non-allowed characters with a dummy in both directions.

I hope for your support and thank you in advance. :-)

**Comment by LausiD** [comment]
thx fpr issue...pls check update FHEM Adapter from github
