### ISSUE TITLE
events ignored from fhem devices with dots in the name

### ISSUE THREAD

**Issue by Signum** [iobroker-community-adapters/ioBroker.fhem#18]
The forum post https://forum.iobroker.net/viewtopic.php?f=20&t=17321 confirms my observation. Any FHEM object that has dots in the name do not trigger events in ioBroker.
I have Homematic switches that are connected to a CUL on an FHEM installation. If I name them "roof.front.light" then it gets discovered by the FHEM adapter but never triggers events. The log reads:

    2018-10-13 20:10:56.597  - info: fhem.0 event (FHEM) "CUL_HM roof.front.light set_on"
But no state in the respective object in ioBroker is changed. I can send state changes from ioBroker though to switch the light on and off.

As soon as I renamed the object to "roof_front_light" I could finally receive change events. Is there a reason for that behavior?

**Comment by LausiD** [comment]
Please check  fhem.0.info.Info.buildDate = 07.10.18 ?
I have no problems with a dummy for example Test.dummy to get the state in ioBroker.

**Comment by Signum** [comment]
Sorry for the late response. Thanks, the issue seems to be gone.
