### ISSUE TITLE
does not work if in fhem the attribute title is set in global

### ISSUE THREAD

**Issue by SilleDE** [iobroker-community-adapters/ioBroker.fhem#197]
If the "attr title" entry is set in "global" in FHEM, the ioBorker adapter cannot establish a connection to FHEM. "Connected to host" and "Heartbeat" are green and "Connected to device or service" is red.

**Comment by LausiD** [comment]
Use global.title in FHEM Adapter Configuration prompt
![grafik](https://user-images.githubusercontent.com/38705515/205495797-82f60db3-9dd4-4a9b-88e1-fb5a261a33a4.png)

**Comment by SilleDE** [comment]
Nice, it works with that. Is this described somewhere or have I overlooked it? If it is not described, a reference to "attr global title" in the documentation would be helpful.
