### ISSUE TITLE
Check ID ... bei jedem Neustart

### ISSUE THREAD

**Issue by Wildbill-Z** [iobroker-community-adapters/ioBroker.fhem#221]
Ich erhalte bei jedem Neustart des FHEM-Adapters folgende warnings im iobroker-log. Wo setze ich an, um das nicht mehr zu bekommen?

`

2023-08-21 12:06:40.965 | warn | > more info FHEM Adapter visit https://github.com/iobroker-community-adapters/ioBroker.fhem/blob/master/docs/de/README.md
-- | -- | --| --
fhem.0 | 2023-08-21 12:06:40.945 | warn | CHECK id: fhem.0.info.Info.lastIOBout
fhem.0 | 2023-08-21 12:06:40.945 | warn | CHECK id: fhem.0.info.Info.lastSend2ioB
fhem.0 | 2023-08-21 12:06:40.945 | warn | CHECK id: fhem.0.info.Info.lastInfo
fhem.0 | 2023-08-21 12:06:40.944 | warn | CHECK id: fhem.0.info.Info.lastError
fhem.0 | 2023-08-21 12:06:40.944 | warn | CHECK id: fhem.0.info.Info.lastWarn
fhem.0 | 2023-08-21 12:06:40.943 | warn | CHECK id: fhem.0.info.Info.numberDevicesFHEMignored
fhem.0 | 2023-08-21 12:06:40.943 | warn | CHECK id: fhem.0.info.Info.alive
fhem.0 | 2023-08-21 12:06:40.942 | warn | CHECK id: fhem.0.info.Info.numberObjectsIOBin
fhem.0 | 2023-08-21 12:06:40.942 | warn | CHECK id: fhem.0.info.Info.numberObjectsIOBoutSub
fhem.0 | 2023-08-21 12:06:40.941 | warn | CHECK id: fhem.0.info.Info.numberObjectsIOBout
fhem.0 | 2023-08-21 12:06:40.941 | warn | CHECK id: fhem.0.info.Info.numberDevicesFHEMsync
fhem.0 | 2023-08-21 12:06:40.940 | warn | CHECK id: fhem.0.info.Info.numberDevicesFHEM
fhem.0 | 2023-08-21 12:06:40.938 | warn | CHECK id: fhem.0.info.Info.roomioBroker
fhem.0 | 2023-08-21 12:06:40.936 | warn | CHECK id: fhem.0.info.Info.buildDate

`

**Comment by mcm1957** [comment]
Please always add the involver versions:
adapter:
admin:
js-controller:
node:
OS/S:

**Comment by Wildbill-Z** [comment]
Sorry, of course, here you are:

adapter: 2.0.5
admin: 6.8.0
js-controller: 4.0.24
node: 16.20.2
OS/S: Debian 12 bookworm

These should all be the stable versions within iobroker or the OS.
Problemoccourded a while ago (maybe 2-3 months?), but I could't get the exact moment as the warnings only appear once after a start/restart. When running, all is working just fine (would say perfect).

**Comment by mcm1957** [comment]
Ok, looks like subotimal logging levels at a first glance.
I'll try to clearify why they have been set this way and eventually reduce to info or debug level.

You cannot avoid them other by setting the log level to error which might block important warnings. So maybe ist best to life with them at the moment if the only are logged at startup.
