### ISSUE TITLE
FHEM restart causes smartnames to be forgotten

### ISSUE THREAD

**Issue by alexjoni** [iobroker-community-adapters/ioBroker.fhem#32]
Everytime I restart fhem, I see in the cloud adapter that my fhem devices are not there anymore.
As I understand adding the devices in the cloud adapter (I use iot) the smartnames gets saved along with the objects:

`  "fhem.0.Shelly1_baie.state": {
    "_id": "fhem.0.Shelly1_baie.state",
    "type": "state",
    "common": {
      "name": "Shelly1_baie state",
      "type": "string",
      "read": true,
      "write": true,
      "role": "state",
      "smartName": {
        "de": "Bad",
        "smartType": "LIGHT"
      }
    },
    "native": {
      "Name": "Shelly1_baie",
      "Attribute": "state",
      "Readings": true,
      "onoff": true,
      "ts": 1554837628678
    },
    "from": "system.adapter.fhem.0",
    "ts": 1554837766451,
    "acl": {
      "object": 1636,
      "state": 1636
    }
  }, `

the same device after fhem restarted:
`"fhem.0.Shelly1_baie.state": {
    "_id": "fhem.0.Shelly1_baie.state",
    "type": "state",
    "common": {
      "name": "Shelly1_baie state",
      "type": "string",
      "read": true,
      "write": true,
      "role": "state"
    },
    "native": {
      "Name": "Shelly1_baie",
      "Attribute": "state",
      "Readings": true,
      "onoff": true,
      "ts": 1557050720356
    },
    "from": "system.adapter.fhem.0",
    "ts": 1557050795118,
    "acl": {
      "object": 1636,
      "state": 1636
    }
  }, `

Any way to prevent that?

**Comment by Apollon77** [comment]
Which fhem version?

**Comment by alexjoni** [comment]
Latest Revision: 18358
File                Rev   Last Change
fhem.pl             18343 2019-01-20

I managed to get lights to work by adding an alias to the name (now when the adapter finds them it registers the Smartname with the alias name, but doesn't set type to light - any idea how to do that)?

But it still doesn't work for rollos: there I had to make some changes (add min0, max100, type=number), and afterwards add the smartname

**Comment by Apollon77** [comment]
I mean which Adapter version? :-)

**Comment by alexjoni** [comment]
1.2.1 installed from github

**Comment by LausiD** [comment]
check fhem.0.info.Configurations.autoSmartName
false= no update smartName restart
true = update smartName every restart
