### ISSUE TITLE
Problems with rooms in ioBroker

### ISSUE THREAD

**Issue by lapidu** [iobroker-community-adapters/ioBroker.fhem#45]
After restarting the adapter i have in ioBroker under "Aufzählungen"- rooms all FHEM romms.
Can i deactivate it?

**Comment by LausiD** [comment]
Yes,  fhem.1.info.Configurations.autoRoom= false

**Comment by lapidu** [comment]
I haven't this option
![ksnip_20191209-194356](https://user-images.githubusercontent.com/28223007/70462996-51657980-1abc-11ea-9bde-478a73776b8a.jpg)

**Comment by LausiD** [comment]
Oh.....you have  V1.3.0 of FHEM Adapter?
Please use V1.4.0 from github

**Comment by lapidu** [comment]
Thank you that's is it. Thank you for the great support.
