### ISSUE TITLE
FHEM does not allow colons in DEVICE names

### ISSUE THREAD

**Issue by freakadings** [iobroker-community-adapters/ioBroker.fhem#46]
First of all great work it's awesome to connect two so powerful HA-Systems so easily!

Now to my issue:
I wanted to use Objects from ioBroker within fhem, so I went to
fhem.0.info.Configurations.allowedIOBin
and entered bshb.0 as Value for this Object.

As the Objects of bshb.0 were updating the dummy-devices were created within fhem:

```
[...]
bshb.0.roomClimateControl_hz_2.RoomClimateControl.boostMode
bshb.0.roomClimateControl_hz_2.RoomClimateControl.low
bshb.0.roomClimateControl_hz_2.RoomClimateControl.operationMode
bshb.0.roomClimateControl_hz_2.RoomClimateControl.schedule
bshb.0.roomClimateControl_hz_2.RoomClimateControl.setpointTemperature
bshb.0.roomClimateControl_hz_2.RoomClimateControl.setpointTemperatureForLevelComfort
bshb.0.roomClimateControl_hz_2.RoomClimateControl.setpointTemperatureForLevelEco
bshb.0.roomClimateControl_hz_2.RoomClimateControl.showSetpointTemperature
bshb.0.roomClimateControl_hz_2.RoomClimateControl.summerMode
bshb.0.roomClimateControl_hz_2.RoomClimateControl.supportsBoostMode
bshb.0.roomClimateControl_hz_2.RoomClimateControl.ventilationMode
bshb.0.roomClimateControl_hz_2.TemperatureLevel.temperature
bshb.0.roomClimateControl_hz_2.TemperatureLevelConfiguration.sensors
bshb.0.roomClimateControl_hz_3.RoomClimateControl.boostMode
bshb.0.roomClimateControl_hz_3.RoomClimateControl.low
bshb.0.roomClimateControl_hz_3.RoomClimateControl.operationMode
bshb.0.roomClimateControl_hz_3.RoomClimateControl.schedule
bshb.0.roomClimateControl_hz_3.RoomClimateControl.setpointTemperature
bshb.0.roomClimateControl_hz_3.RoomClimateControl.setpointTemperatureForLevelComfort
bshb.0.roomClimateControl_hz_3.RoomClimateControl.setpointTemperatureForLevelEco
bshb.0.roomClimateControl_hz_3.RoomClimateControl.showSetpointTemperature
bshb.0.roomClimateControl_hz_3.RoomClimateControl.summerMode
bshb.0.roomClimateControl_hz_3.RoomClimateControl.supportsBoostMode
bshb.0.roomClimateControl_hz_3.RoomClimateControl.ventilationMode
bshb.0.roomClimateControl_hz_3.TemperatureLevel.temperature
bshb.0.roomClimateControl_hz_3.TemperatureLevelConfiguration.sensors
bshb.0.roomClimateControl_hz_4.RoomClimateControl.boostMode
bshb.0.roomClimateControl_hz_4.RoomClimateControl.low
bshb.0.roomClimateControl_hz_4.RoomClimateControl.operationMode
bshb.0.roomClimateControl_hz_4.RoomClimateControl.schedule
bshb.0.roomClimateControl_hz_4.RoomClimateControl.setpointTemperature
bshb.0.roomClimateControl_hz_4.RoomClimateControl.setpointTemperatureForLevelComfort
bshb.0.roomClimateControl_hz_4.RoomClimateControl.setpointTemperatureForLevelEco
bshb.0.roomClimateControl_hz_4.RoomClimateControl.summerMode
bshb.0.roomClimateControl_hz_4.RoomClimateControl.supportsBoostMode
bshb.0.roomClimateControl_hz_4.RoomClimateControl.ventilationMode
bshb.0.roomClimateControl_hz_4.TemperatureLevel.temperature
bshb.0.roomClimateControl_hz_4.TemperatureLevelConfiguration.sensors
bshb.0.ventilationService.VentilationDelay.delay
bshb.0.ventilationService.VentilationDelay.devices
[...]
```
But some are missing so i searched around and found that every object which is missing has colons in its name.  e.q.: "bshb.0.hdm:HomeMaticIP:3014F711A044405538592818"
which, in this case, is problematic because these are the actual sensors and actors.

This should be why these devices aren't ported to fhem, since fhem does not support colons in devicenames anymore. ( https://wiki.fhem.de/wiki/Ger%C3%A4tename )

Could you please implement a function that replaces colons ":" with e.q. underscores "_" or better: let the user decide which character he want's to use?

Thank you in advance and keep up this great work!

**Comment by LausiD** [comment]
@freakadings 
thx for this issue...it will help to make this adapter better :-)
Pls update adapter from github V1.4.0 10.12.19
Now ":" "#" "-" have been replaced by "_"
Do you really need  to decide which character to use?

**Comment by freakadings** [comment]
Thanks for the quick response :)
No, i dont need to customise the character, it was just a suggestion. Underscore is fine :)

(sorry beginners question but: how do i update from github? I'm running iobroker in a docker container)

**Comment by LausiD** [comment]
Section 8 FAQ "Update Adapter über github"
https://github.com/iobroker-community-adapters/ioBroker.fhem/blob/master/docs/de/README.md

**Comment by freakadings** [comment]
Danke ;)

Works great now, all Devices have been created.
Thanks a lot!

**Comment by LausiD** [comment]
Perfect.....have fun with iobroker and FHEM :-)
