### ISSUE TITLE
compact mode stop

### ISSUE THREAD

**Issue by handy80** [iobroker-community-adapters/ioBroker.fhem#51]
@Apollon77  bat mir hier ein issue anzulegen... :-) 

log wurde endlos geschrieben nachdem ich den admin-adapter geupdated hatte oder den FHEM-Pi (anderer als der ioBroker-Pi neugestartet hatte)
habe so viele adapter im compact mode und auch alle in einer group
 
https://github.com/iobroker-community-adapters/ioBroker.fhem/blob/330234314a1ffde93f066154dc9a5b98a2563c2a/main.js#L1779

Forum-Issue:
https://forum.iobroker.net/topic/28752/log-explosion-12gb-conf-redis-redis

**Comment by Apollon77** [comment]
@LausiD Hey, Compact mode aktuell kaputt!!

Bitte sicherstellen das alle "setTimeouts" und "setIntervals" in jedem Fall einer Variable zugewiesen sind UND das du im "on(unload)" alle diese Timer und Intervalle sauber beendest! (clearTimeout).

Hast Du Zeit das anzugehen und zu fixen?

**Comment by LausiD** [comment]
@Apollon77 
Danke für die Info :-(
Kann ich leider nicht wie du locker aus dem Ärmel schütteln :-)
Muss mich erst schlau machen und komme frühestens Sa Abend dazu....
Falls du Zeit und Lust hast gerne ?

**Comment by Apollon77** [comment]
Ich hab bei den anderen Community Devs mal gefragt ... sonst reicht Wochenende natürlich auch. Wenn Du
 Unterstützung brauchst sag jederzeit Bescheid!

**Comment by GermanBluefox** [comment]
https://github.com/iobroker-community-adapters/ioBroker.fhem/commit/85c37dcb03a6362f0eee029cb08855414053695a

**Comment by LausiD** [comment]
Vielen Dank an Bluefox!
habe gerade den compact mode lange getestet....bekomme mit adapter.restart(); noch die gleichen Fehlermeldungen:  fhem.0 (COMPACT) Objects database not connected [main] [firstCheck] [getSetting] usw 
Sieht so aus als ob bei adapter.restart die Datenbank nicht verbunden wird ?????
Ohne compact mode keine Probleme

**Comment by Apollon77** [comment]
Doch die wird verbunden. Aber für den alten „Prozess“wird die dB gekillt.  Also irgend etwas versucht da noch Dinge zu tun nach dem unload. Das muss man finden.

**Comment by Apollon77** [comment]
Gerade geschaut ... adapter restart ist im eimer mit compact mode ... adapter restart macht ein direktes terminate und dabei wird kein unload aufgerufen. ich lege ein jscontroller issue an

**Comment by Apollon77** [comment]
Bitte vrsuch mal mit controller 2.2.8

**Comment by LausiD** [comment]
@Apollon77 
Habe noch ein Problem.....
Ist beim Start Adapter FHEM über Telnet nicht erreichbar oder offline kommen folgende Fehlermeldungen:

 fhem.0 | 2020-02-21 22:34:04.715 | error | (COMPACT) Error: connect ECONNREFUSED 127.0.0.1:7072     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
-- | -- | -- | --
fhem.0 | 2020-02-21 22:34:04.714 | error | (COMPACT) uncaught exception: connect ECONNREFUSED 127.0.0.1:7072

Im compact mode führt das zu einem 
> compactgroup controller 1 terminated

Hast du eine Idee?  Danke

**Comment by Apollon77** [comment]
Jupp. Muss ein on(„error“, ...) Event handler an deine tcp Verbindung hängen. Dann bekommst funds nen callback und es fliegt keine exception.

**Comment by LausiD** [comment]
Unter function main() eingefügt:
telnetOut.on('error', err => adapter.log.warn('ERROR: ' + err));
Leider ohne Erfolg
