### ISSUE TITLE
New Feature: Lets users configure the internals which they want

### ISSUE THREAD

**Issue by syryna** [iobroker-community-adapters/ioBroker.fhem#52]
Hi,

I use this module as I have some Enocean devinces running.

I want to see the RSSI values and they are Internals, but unluckily only NAME and TYPE is transmitted.

For the moment I changed this line:
const allowedInternalsS = ['TYPE', 'NAME', 'USB300_RSSI', 'USB300_ReceivingQuality'];

Could you maybe add a configuration page which allows users to freely choose the values or attributes which they want to see in ioBroker. 

Regards, Mike
![iobroker_fhem](https://user-images.githubusercontent.com/9818422/75117467-e0bd0a80-5671-11ea-84db-ec04061751e2.png)

**Comment by LausiD** [comment]
Hi Mike,
thx for issue.....it's possible, pls check objekt fhem.0.info.Configurations.allowedInternals.
But Internals are only synced at the start of adapter :-(
Better way: userreadings in FHEM 
https://forum.iobroker.net/topic/5031/fhem-adapter/343

LausiD

**Comment by syryna** [comment]
@LausiD thanks so much.

first of all sorry that I did not see the Configuration entires under info. 

then thanks a lot for the hint about the internals being only read during adapter startup. I managed to create UserReadings and it is working like a charm.

Mike
