### ISSUE TITLE
Überlastung der Telnet Verbindung

### ISSUE THREAD

**Issue by lammy000** [iobroker-community-adapters/ioBroker.fhem#59]
Hi,

ich habe die Erfahrung mit dem Fritz Adapter gemacht das dein fhem Modul den SET befehlt ausführt obwohl sich der Wert von dem eigentlichen Objekt nicht geändert hat.
Beispiel:
11:01 Uhr - fritzdect0.bla - wert - 0 -> set fritzdect0.bla 0

11:02:00 Uhr - abfrage des Fritzdect Adapters ob sich was geändert hat
11:02:02 Uhr - fritzdect0.bla - wert - 0 -> set fritzdect0.bla 0
!! Wieso muss der Befehl ausgeführt werden wenn sich das Objekt nicht geändert hat? !!

Vielleicht bedenke ich etwas nicht aber ich Frage bei meinen JavaScripts immer nur Änderungen und schreibe dann.

In meinem Fall ist es so, das ich relativ aktuelle Daten der FritzDect Adapters brauche da ich Dort Stromverläufe mit verfolge. Daher fragt der Adapter alle 2 Sekunden ab was zum absoluten Sterben des Moduls geführt hat. Ein Befahl hat gute 5-10 Sekunden gedauert bis er ankam. Was auch nach zu vollziehen ist :-)

Kannst du dort was nach coden ?

VG

**Comment by lammy000** [comment]
Hi,

update ist durch. Leider ist es immer noch so das er hängt wenn der FritzDect Adapter die Werte rüber ballert.
Ich Übertrage Werte des FritzDect Adapters wie z.b. die Aktuelle Leistungsaufnahme zu Fhem um den Betriebsstundenzähler zu nutzen. Ich steige gerade von FHEM auf ioBroker um und möchte eigentlich das weiter nutzen was bei fhem gut läuft :-)

**Comment by lammy000** [comment]
VG lammy

**Comment by LausiD** [comment]
Ok, aber geht schon etwas flotter, oder?
Wieviele Objekte mit fhem.0.info.Configurations.allowedIOBin überträgst du von ioB zu Fhem?
(siehe fhem.0.info.Info.numberObjectsIOBout)
Wenn du alle 2Sek den Fritzdect Adapter aktualisierst werden vermutlich alle Objekte neu eingelesen und deshalb vom FHEM Adapter als Änderung geschickt.
Verlängere zum Test mal die Zeit von 2 auf 10 Sek

**Comment by lammy000** [comment]
fhem.0.info.Info.numberObjectsIOBout = 750
ja die werte werden neu eingelesen aber vom wert her nicht geändert. Daher meine Idee vor dem Ausführen des "fhem set ..." abzufragen ob sich der Wert wirklich geändert hat. Das sollte schneller gehen als den Telnet Befehl aus zu führen :-)

**Comment by lammy000** [comment]
ach so und ja das lief flotter aber bei der 2 Sekunden Variante immer noch nicht praktikabel :-)

**Comment by LausiD** [comment]
Respekt.....du möchtest alle 2 Sek 750 Änderungen übertragen
Und du brauchst wirklich alle 750 Objekte in FHEM?
Der FHEM Adapter reicht die Änderungen nur durch...da ist nichts zu machen

**Comment by lammy000** [comment]
Hi,
der FHEM Adapter reicht aktuell alles durch egal ob de Wert sich wirklich geändert. Er nimmt scheinbar jede Aktualisierung eines Wertes mit egal ob nach der Aktualisierung ein anderer Wert drin steht. Kann man es nicht über einen Prozent Wert Regeln der vor dem SET Befehl die Daten die sich im RAM Befinden ausließt ? Da müsstest du aber jeden Wert als Variable in RAM rein ballern oder alle Geräte mit Ihren Werten als neue Tabelle in ioBroker erzeugen. Wäre auch nur Semi sicher da sich ja in FHEM etwas ändern kann :-) mhhh ich merke das könne problematisch werden ...

**Comment by lammy000** [comment]
Die 750 Geräte werden ja nicht alle aktualisiert und ich habe einfach alle KNX Geräte in fhem gespiegelt. Nur die Dect fritzbox Geräte werden alle 2 Sekunden neu beschrieben. Ich habe den Adapter aber auch schon angepasst und bin mit dem Entwickler in Kontakt das er meinen Ansatz "Schreib nur was wenn es wirklich notwendig ist" auch übernimmt.

**Comment by LausiD** [comment]
Wurde im Adapter schon was geändert? 
Hat sich Problem dadurch erledigt?

**Comment by lammy000** [comment]
Habe den FritzDect adapter angepasst damit er nicht alles Überträgt.

**Comment by LausiD** [comment]
In V1.5.0 werden mit allowedIob nur noch geänderte States nach FHEM übertragen.
Wenn du mal testen möchtest ?
