### ISSUE TITLE
Reduce / Combine values before sending them to FHEM

### ISSUE THREAD

**Issue by freakadings** [iobroker-community-adapters/ioBroker.fhem#60]
It's me again :)
I wonder if it's possible to reduce the amount of dummys created within fhem by combining similar names. 
E.q. in ioBroker I got a thermostat which delivers 14 values. In FHEM for each value a dummy with only one status is created so there are a lot of dummys since i have more than one heater.

![iobroker](https://user-images.githubusercontent.com/31108657/79587351-b6685600-80d2-11ea-8669-a602646abddb.png)

In my case the names are divided by '.' the first three parts are the same and could be the device name fourth and fifth could be the name of the reading within FHEM. 
Right now i have to make another additional dummy to send the radings to and make it "nice".

Maybe i'm the only one who has this problem linke the ':' issure from earlier.

**Comment by LausiD** [comment]
Do you really need all 14 values of every thermostat in FHEM?
The idea of this function was a possibility to send special values from ioB to FHEM

**Comment by freakadings** [comment]
Not really but it's auto generated.
But even if i needed only two values, wouldn't it be better to have only one dummy in fhem than two?

**Comment by PichlAlex** [comment]
sidenote: i solve this issue using MQTT

i publish all needed from ioBroker to MQTT and in fhem i create a dummy with multiple readings and map this:

MQTT Client in FHEM:
```
defmod myBroker MQTT2_CLIENT 10.0.0.2:1883
attr myBroker autocreate no
attr myBroker clientId homei-FHEM
attr myBroker room 9.06 MQTT
attr myBroker username mqttuser
```

to Publish events in FHEM:
```
defmod mqttGeneric MQTT_GENERIC_BRIDGE mqtt Garten_Regenwassertank,WZ_Thermostat_Climate
attr mqttGeneric IODev myBroker
attr mqttGeneric globalDefaults base={"/home-FHEM/$device"}
attr mqttGeneric globalPublish measured-temp:topic={"$base/$name"} battery:topic={"$base/$name"} batteryLevel:topic={"$base/$name"}  Activity:topic={"$base/$name"} desired-temp:topic={"$base/$name"} *:resendOnConnect=last
attr mqttGeneric room 9.06 MQTT
```

and the "dummy" that represents the object from ioBroker
```
defmod Garten_Wasserwerk MQTT2_DEVICE home_FHEM
attr Garten_Wasserwerk IODev myBroker
attr Garten_Wasserwerk readingList Wasserwerk-Michi:/Wasserwerk/ampere.* ampere\
Wasserwerk-Michi:/Wasserwerk/on_off:.* on_off\
Wasserwerk-Michi:/Wasserwerk/TankCritical:.* TankCritical\
homeMichi_FHEM:/Wasserwerk/ampere:.* ampere\
homeMichi_FHEM:/Wasserwerk/on_off:.* on_off\
homeMichi_FHEM:/Wasserwerk/TankCritical:.* TankCritical
attr Garten_Wasserwerk room 9.06 MQTT
attr Garten_Wasserwerk stateFormat ampere A, Relais=on_off, Critical=TankCritical
```

installation needed before you can do this on FHEM host:
my used howtos: https://wiki.fhem.de/wiki/MQTT bzw https://www.vultr.com/docs/how-to-install-mosquitto-mqtt-broker-server-on-ubuntu-16-04

```
apt-get install mosquitto mosquitto-clients
service mosquitto status
mosquitto_passwd -c /etc/mosquitto/passwd mqttuser
cpan install Net::MQTT:Simple
cpan install Net::MQTT:Constants

nano /etc/mosquitto/conf.d/default.conf
	allow_anonymous false
	password_file /etc/mosquitto/passwd
	
systemctl restart mosquitto
```

now test MQTT
	1. Window:   mosquitto_sub -t "test" -u "mqttuser" -P "mypassword"
	2. window: mosquitto_pub -t "test" -m "message from mosquitto_pub client" -u "mqttuser" -P "mypassword"
	3. in FHEM: set myBroker publish test someMessageToSend

how to get all messages from mosquitto (and not a specific topic):
mosquitto_sub -v -t "#" -u "mqttuser" -P "xxxxx"

**Comment by freakadings** [comment]
Thank you very much for your examples!
Could you please explain how you solved the part how you publish data from iobroker to mqtt and how you configured the used adapter(s)? Since this is the diffcult part for me...
