### ISSUE TITLE
Adapter startet nicht nach Update auf 1.5.0

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.fhem#66]
Habe zuerst nur ein Update gemacht, jetzt aber den Adapter komplett deinstalliert und wieder installiert.
js-controller: 3.1.4
Node: 12.16.3
NPM:6.14.4

Selber Fehler:
`

host.iobroker | 2020-05-14 19:17:42.798 | info | Restart adapter system.adapter.fhem.0 because enabled
-- | -- | -- | --
host.iobroker | 2020-05-14 19:17:42.798 | error | instance system.adapter.fhem.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
host.iobroker | 2020-05-14 19:17:42.798 | error | Caught by controller[0]:     at process._fatalException (internal/process/execution.js:164:25)
host.iobroker | 2020-05-14 19:17:42.798 | error | Caught by controller[0]:     at process.emit (events.js:322:22)
host.iobroker | 2020-05-14 19:17:42.798 | error | Caught by controller[0]:     at process.<anonymous> (/opt/iobroker/node_modules/iobroker.fhem/main.js:3162:15)
host.iobroker | 2020-05-14 19:17:42.798 | error | Caught by controller[0]: TypeError: telnetOut.stop is not a function
host.iobroker | 2020-05-14 19:17:42.798 | error | Caught by controller[0]:               ^
host.iobroker | 2020-05-14 19:17:42.798 | error | Caught by controller[0]:     telnetOut.stop();
host.iobroker | 2020-05-14 19:17:42.797 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.fhem/main.js:3162
fhem.0 | 2020-05-14 19:17:42.773 | debug | (13840)  [stateChange] stateChange: fhem.0.info.Commands.sendFHEM done  {"val":"done","ack":true,"ts":1589476662754,"q":0,"from":"system.adapter.fhem.0","user":"system.user.admin","lc":1589476662754}
fhem.0 | 2020-05-14 19:17:42.770 | info | (13840) > processed 1 event(s) of FHEM saved during synchro
fhem.0 | 2020-05-14 19:17:42.770 | info | (13840) STEP 14 ==== processed saved event(s) of FHEM

`

**Comment by Apollon77** [comment]
Bitte 1.5.1 von GitHub versuchen, da ist der Fehler weg - die Ursache dürfte aber ein anderer Fehler sein - den sehen wir aber erst dann

**Comment by guergen1** [comment]
Läuft.
Im Debuglog KEINE Auffälligkeiten!
Danke!
