### ISSUE TITLE
Error when state is not existing

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.fhem#68]
@LausiD https://sentry.iobroker.net/share/issue/61899b7dea694e53ac29196b7ba623fd/

Wis muss sich der Code denn verhalten wenn das state gar nicht existiert?

**Comment by LausiD** [comment]
@Apollon77 
Problem ist noch in Zeile  2857 if (stateG.val !== command.val) {
Die Idee war nur states zu schreiben wenn sich der Zustand aus FHEM geändert hat. Hatte den Eindruck ein getstate geht schneller als ein setstate. Deshalb das getstate und der Vergleich danach.
Warum an der Stelle noch nicht vorhandene Id's ankommen muss ich noch suchen....
Wenn an der Stelle kein state vorhanden ist kann der Vorgang abgebrochen werden.
Fehlt vermutlich nur die passende Abfrage :-)

Vielen Dank und Gruß
LausiD

**Comment by Apollon77** [comment]
Das hat mit nodejs nix zu tun. EIn State kann einen Wert haben oder halt nicht und wenn ein State noch nie einen gesetzten wert hatte kommt bei getState ein null zurück. Du musst das also checken bei einem getState ob da ein Objekt zurückkommt. "Jull" haeisst sob´viel wie "hat bisher noch nie einen Wert gehabt"

**Comment by LausiD** [comment]
@Apollon77 
Sollte jetzt passen, oder?

**Comment by Apollon77** [comment]
spontan ja, mach doch mal neue Version, dann sehen wirs

**Comment by LausiD** [comment]
Fix in 1.5.3
