### ISSUE TITLE
Report for the developper

### ISSUE THREAD

**Issue by keihuli** [iobroker-community-adapters/ioBroker.fhem#70]
I get this error warnings, bcause there is standing "report this to the devolopper' I created this issue.
I am using: node: v12.16.2, js-controller: 3.1.4

`Betriebssystem
linux
Betriebssystem
linux
Architektur
arm
CPUs
4
Geschwindigkeit
900 MHz
Modell
ARMv7 Processor rev 5 (v7l)
RAM
926.08 MB
System Betriebszeit
37 T. 09:05:39
Node.js
v12.16.2 (Es gibt eine neuere Version: v12.17.0)
NPM
6.14.4
Festplatte Größe
29.28 GB
Festplatte frei
26.41 GB
Anzahl der Adapter
292
Betriebszeit
1 T. 13:39:14
Aktive Instanzen
13
Hostname
ioBroker-RasPi
`

  |   |   |  
-- | -- | -- | --
fhem.0 | 2020-06-01 19:08:24.794 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:08:24.793 | warn | (9278) State value to set is invalid for fhem.0.CUL_WS_5.state: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:08:16.525 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:08:16.525 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.seqno: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:08:16.518 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:08:16.517 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.total: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:08:16.510 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:08:16.509 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.peak_cnt: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:08:16.502 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:08:16.501 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.current: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:08:16.494 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:08:16.493 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.tsecs: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:08:16.484 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:08:16.483 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.total_cnt: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:08:16.476 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:08:16.475 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.RAW: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:08:16.469 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:08:16.468 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.peak: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:08:16.461 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:08:16.460 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.current_cnt: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:08:16.453 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:08:16.452 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.state: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:07:57.177 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:07:57.176 | warn | (9278) State value to set is invalid for fhem.0.CUL_WS_1.state: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:04:13.532 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:04:13.531 | warn | (9278) State value to set is invalid for fhem.0.CUL_WS_6.state: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:03:14.951 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:03:14.950 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.peak_cnt: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:03:14.945 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:03:14.944 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.total: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:03:14.939 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:03:14.938 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.seqno: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:03:14.933 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:03:14.933 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.current_cnt: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:03:14.928 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:03:14.927 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.RAW: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:03:14.923 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:03:14.922 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.peak: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:03:14.917 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:03:14.916 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.total_cnt: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:03:14.910 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:03:14.909 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.tsecs: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:03:14.903 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:03:14.902 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.current: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-01 19:03:14.896 | warn | (9278) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-01 19:03:14.895 | warn | (9278) State value to set is invalid for fhem.0.CUL_EM_9.state: The state property "ts" has the wrong type "undefined" (should be "number")!

`

**Comment by LausiD** [comment]
Thx for the report.
Version of FHEM adapter?

**Comment by keihuli** [comment]
Sorry I forget fhemadapter 1.3.0. My fhem instance is uptodate...

**Comment by LausiD** [comment]
Ok pls update FHEM adapter from 1.3.0 to 1.5.3

**Comment by Apollon77** [comment]
@LausiD 1.5.3 for stable?

**Comment by keihuli** [comment]
I am not sure if it is stable, because in 1.3.0 i can press a button in the objects tab of iobroker (it is an fs20 rsu [switch)], and my rollo works...
In 1..3 i am getting this warning:
```
hem.0	2020-06-02 22:43:53.096	warn	(12527) State value to set is invalid for fhem.0.rollo_kai_r.state: The state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0	2020-06-02 22:43:53.066	warn	(12527) This value will not be set in future versions. Please report this to the developer.

```

And in 1.5.2 i am getting:

```
fhem.0 | 2020-06-02 22:53:23.272 | warn | (13242) unhandled stateChange: fhem.0.rollo_kai_r.Auf \| true > stateChange - no match !state.ack & fhemObjects[id]{"val":true,"ack":false,"ts":1591131203264,"q":0,"from":"system.adapter.admin.0","use
-- | -- | -- | --
```

In both version the raw definition is the same:
`{
  "from": "system.adapter.fhem.0",
  "ts": 1547675485200,
  "user": "system.user.admin",
  "common": {
    "name": "rollo.kai.r Auf",
    "role": "button",
    "type": "boolean",
    "write": true
  },
  "native": {
    "Name": "rollo.kai.r",
    "Attribute": "Auf",
    "possibleSets": true,
    "noArg": true
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "fhem.0.rollo_kai_r.Auf",
  "type": "state"
}
`

Did you need more information?

**Comment by LausiD** [comment]
fhem.0.rollo_kai_r.Auf \| true > stateChange - no match !state.ack & fhemObjects[id]
It means.....object wit the name "fhem.0.rollo_kai_r.Auf \" was not found
The problem is \ at the end.

**Comment by LausiD** [comment]
pls check again
1. insert rollo.kai.r in fhem.0.info.Debug.activate
2. update FHEM adapter from github 1.5.2 (03.06.20)
3. tell me the events from log after press the button
thx

**Comment by keihuli** [comment]
I put the value into Wert column, and stopped fhem and restarted it, after that I get

**rollo.kai.r:**
```
fhem.0 | 2020-06-04 22:15:41.076 | info | (17872) rollo.kai.r \| stateChange (in): fhem.0.rollo_kai_r.on true  {"val":true,"ack":false,"ts":1591301741068,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1591301741068}
-- | -- | -- | --
```
**rollo_kai_r:**

fhem.0 | 2020-06-04 22:18:51.233 | info | (18125) rollo.kai.r \| stateChange (in): fhem.0.rollo_kai_r.on true  {"val":true,"ack":false,"ts":1591301931226,"q":0,"from":"system.adapter.admin.0","user":"system.user.admin","lc":1591301931226}
-- | -- | -- | --


Here you see the complete log:
[start.log](https://github.com/iobroker-community-adapters/ioBroker.fhem/files/4732536/start.log)

**Comment by LausiD** [comment]
No more messages after stateChange (in): fhem.0.rollo_kai_r.on true ?
Did you wait until STEP15  ( end of synchro) ?

**Comment by keihuli** [comment]
Solved!!! Here is there story:

I wait about 30 minutes, but the adapter remains in step 10
Awards I uncomment all ioBroker rooms in fhem without kairollo
and then I deleted all fhem objects in iobroker, but two elements cannot be deleted by me.... The error in IOBroker is:
Fehler [object Object]
Then I am starting the adapter again and he still remains in step 10. Last message is:
`fhem.0	2020-06-05 07:34:32.452	info	(18056) > delete unused objects (*) > delete 0 channel(s) and 2 state(s)
`
The two objects which I can't delete are old fhem objects, which don't exists anymore in fhem. 
After Googling I deleted  these two objects in objects.json...
Now everthing works.... ;)
Maybe It could be helpfull that the adapter wrote that he cannot delete an object...

Did you need some more information, may be the objects.json?

**Comment by LausiD** [comment]
Pls check again with update from github.
The adapter write the error now :-)
