### ISSUE TITLE
fhem.0 yellow "got terminate signal. Checking desired PID warnings"

### ISSUE THREAD

**Issue by vdi-cloud** [iobroker-community-adapters/ioBroker.fhem#73]
iobroker was all green before my fhem server had disk full problems (which I fixed, i.e. fhem is working fine again). Now in iobroker server (Pi4 on ) fhem-adapter 1.5.2 (I tried V1.3.0 as well) remains yellow, telnet to fhem server is working fine. telnet on fhem has no SSL enabled, I tried w/ and w/o password setting - no change:

pi@iobroker:~ $ telnet fhemLAN 7072
Trying 192.168.178.55...
Connected to fhemLAN.fritz.box.
Escape character is '^]'.

fhem>>     

debug log is showing following warnings:
2020-06-14 17:45:40.876  - warn: fhem.0 (5323) Got terminate signal. Checking desired PID: 0 vs own PID 5323
2020-06-14 17:45:40.882  - warn: fhem.0 (5323) Got terminate signal. Checking desired PID: 12300 vs own PID 5323
...

iobroker is running on buster 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l
Node.js: v10.21.0
NPM: 6.14.4

**Comment by LausiD** [comment]
https://github.com/iobroker-community-adapters/ioBroker.fhem/tree/master/docs/de#%C3%BCberblick
I check the telnet connection with Putty...see link

**Comment by vdi-cloud** [comment]
problem is solved. I have deleted telnetPort device in fhem and recreated it now according to the description. it is working fine again. Also I have switched back to an earlier iobroker setup with fhem 1.5.1 adapter. Not really sure what was causing the problem. If 1.5.3 might work - my be I try it out later. Ticket can be closed.
