### ISSUE TITLE
State value to set is invalid for fhem.0 ...

### ISSUE THREAD

**Issue by matusbr** [iobroker-community-adapters/ioBroker.fhem#75]
Heute ist mir aufgefallen dass ich zu sämtlichen meiner FHEM Komponenten diese Meldung bekomme.
Dieses Warning müllt natürlich mein LOG voll. Was muss ich ändern?

fhem.0 | 2020-06-27 15:07:34.910 | warn | (2227) State value to set is invalid for fhem.0.kizFuehl.temperature: The state property "ts" has the wrong type "undefined" (should be "number")!
-- | -- | -- | --
fhem.0 | 2020-06-27 15:07:34.834 | warn | (2227) This value will not be set in future versions. Please report this to the developer.

FHEM.Adapter ist in de V. 1.3.0 installiert
Node.js v12.18.1
NPM 6.14.5
Alles auf dem neusten Stand, da ich aufgrund eines ioBrokers meinen NUC heute neu aufgesetzt habe.
Läuft alles im Docker und die FHEM ist ein RPI.

Vielen Dank für deine Hilfe.

**Comment by LausiD** [comment]
Hatten wir schon mal....
https://github.com/iobroker-community-adapters/ioBroker.fhem/issues/71
Update von github auf 1.5.2 und Meldung ist weg

Gruß LausiD

**Comment by matusbr** [comment]
Top Danke für die Lösung. Ich habe die aktuellste 1.5.6 installiert und das Problem ist behoben.
Danke Marcus
