### ISSUE TITLE
Values of batteryState not sent to iobroker

### ISSUE THREAD

**Issue by Wildbill-Z** [iobroker-community-adapters/ioBroker.fhem#82]
I have some FHT thermostats and some FHHTK door sensors. Within FHEM i have datapoints "battery" and "batteryState" for the FHTs which both have actual date and time (within some minutes) and only datapoints "batteryState" for the FHHTKs, also with actual date and time.
However in iobroker, only the datapoints battery from the FHTs are set. The datapoints batteryState from the FHT or FHHTK have dates from June or July and don't get set, even if i restart FHEM, the adapter or the hole iobroker.
Is there some filter, why batteryState is not synced between iobroker and FHEM but battery, which is not available for the door sensors?

Greetings, Jürgen

**Comment by LausiD** [comment]
Pls set fhem.0.info.Configurations.syncUpdate = true and check again

**Comment by Wildbill-Z** [comment]
Perfect, seems like that did the trick. All datapoints batteryState and battery now seem to be updated every few minutes. Thanks. I'll close the issue.
