### ISSUE TITLE
ioBroker aktualisiert Werte nicht

### ISSUE THREAD

**Issue by petterpet** [iobroker-community-adapters/ioBroker.fhem#85]
Wenn in FHEM zweimal der gleiche Wert in ein Reading geschrieben wird, löst ioB beim zweiten Mal kein Event aus.
Skripte, die auf "wurde aktualisiert" triggern, starten somit nicht mehr bis sich der Wert im Objekt geändert hat.
Früher war dies möglich, bitte beheben.

**Comment by LausiD** [comment]
Bitte fhem.0.info.Configurations.syncUpdate auf true setzen und funkioniert wie früher.
In der nächsten Version wieder als defaut Wert

**Comment by petterpet** [comment]
Das hat geholfen. Vielen Dank!
