### ISSUE TITLE
javascript.0	2020-11-03 15:52:04.366	warn	(1247) missing or unrecognized endTime expression: NaN

### ISSUE THREAD

**Issue by ausbremen** [iobroker-community-adapters/ioBroker.fhem#89]
Hi,

since some time I got warnings in my iobroker log from the fhem Adapter:

javascript.0 | 2020-11-03 15:54:55.591 | warn | (1247) missing or unrecognized endTime expression: NaN
-- | -- | -- | --
javascript.0 | 2020-11-03 15:54:53.091 | warn | (1247) missing or unrecognized endTime expression: NaN
javascript.0 | 2020-11-03 15:53:28.186 | warn | (1247) missing or unrecognized endTime expression: NaN
javascript.0 | 2020-11-03 15:53:25.685 | warn | (1247) missing or unrecognized endTime expression: NaN
javascript.0 | 2020-11-03 15:52:38.409 | warn | (1247) missing or unrecognized endTime expression: NaN
javascript.0 | 2020-11-03 15:52:35.909 | warn | (1247) missing or unrecognized endTime expression: NaN
javascript.0 | 2020-11-03 15:52:06.865 | warn | (1247) missing or unrecognized endTime expression: NaN
javascript.0 | 2020-11-03 15:52:04.366 | warn | (1247) missing or unrecognized endTime expression: NaN
fhem.0 | 2020-11-03 15:51:27.475 | info | (553) stateChange (out): fhem.0.info.Commands.sendFHEM \| set fhem.0.alive on-for-timer 360 > set fhem.0.alive on-for-timer 360

I pretty shure, that I didn´t change something...
but as it´s a warning, I don´t know if it matters... the fhem adapter seem to do what he should do :)

Best regards
Holger

**Comment by Apollon77** [comment]
That error message is not found in javascript or fhem adapter, so where it somes from? Needs to be a custom script. check your script please

**Comment by ruslanin** [comment]
Just put it here for information.
I had the similar error when moved my iobroker instance on new PCB.
Error  "missing or unrecognized endTime expression" was generated by getState function because i forgot to create custom user objects in objects tree, were i have store time values used in script
