### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by stephan1827** [iobroker-community-adapters/ioBroker.fhem#92]
I updated the FHEM docker container to the latest version and now I get this error message from the iobroker adapter

(8774) > SyntaxError jsonlist2 of FHEM device --> stop instance fhem.0 [main] [syncFHEM]

Stephan

**Comment by LausiD** [comment]
https://forum.iobroker.net/topic/39942/fehlende-devices-und-zust%C3%A4nde-im-fhem-adapter

**Comment by LausiD** [comment]
fixed with  98_telnet.pm 23434 2020-12-29 20:22:05Z rudolfkoenig
