### ISSUE TITLE
sendFHEM not working

### ISSUE THREAD

**Issue by ch90045** [iobroker-community-adapters/ioBroker.fhem#95]
I did set up everything as per readme.

I can send commands via telnet, Adapter claims to be connected and i do get messages FROM FHEM but using the sendFHEM datapoint does not get an ACK hence the command is not executed.

Please advise which logs you need.

i am using version 1.5.3

TIA

Christian

**Comment by Apollon77** [comment]
Please provide a debug log from such an action

**Comment by LausiD** [comment]
https://forum.iobroker.net/topic/39942/gel%C3%B6st-fehlende-devices-und-zust%C3%A4nde-im-fhem-adapter?_=1617655946419
