### ISSUE TITLE
State "fhem.0.info.Info.TEST" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by Wildbill-Z** [iobroker-community-adapters/ioBroker.fhem#96]
Since update of Javascript controller to version 3.2.16 (latest stable) I allways get some warnings when starting the FHEM adapter:

`

fhem.0 | 2021-03-07 16:28:58.034 | warn | (6059) State "fhem.0.info.Info.TEST" has no existing object, this might lead to an error in future versions
-- | -- | -- | --

`

I stopped FHEM adapter, deleted hole tree and restarted but the warning just came back.
Is there something I could do by myself?
In fhem.0.info.Info there is no datapoint TEST. And none of my scripts would trigger for it.

Greetings, Jürgen

**Comment by LausiD** [comment]
fixed in github  builddate: 10.02.21
pls update from github and check again :-)

Greetings, LausiD

**Comment by Wildbill-Z** [comment]
@LausiD Thanks, problem seems to be solved. I just wondered as I was on version 1.5.3 and after updating via Github (the "cat" in iobroker), I still saw version 1.5.3. But nevertheless, the message is gone, I'll close the issue.
